### ISSUE TITLE
Bug in ValidatePath.hpp

### ISSUE THREAD

**Issue by nobodyczcz** [gppc-dev/startkit-classic#21]
Mark reported the following issue:

> fyi line 138 of validator/ValidatePath.hpp in the gppc startkit has for (size_t i = 0; i < S-1; ++i) { in which S-1 wraps to a very large number if the path is empty, resulting in a segfault 

@heavenfall could you take a look, thanks!

**Comment by heavenfall** [comment]
Can confirm this bug.

**Comment by heavenfall** [comment]
Fixed
